<?php

namespace Brooter\PaymentBundle\Repository;

/**
 * PaymentTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
