brooter_payment_homepage:
    path:     /
    defaults: { _controller: BrooterPaymentBundle:Default:index }

brooter_payment_done:
    path:     /done
    defaults: { _controller: BrooterPaymentBundle:Payment:captureDone }

brooter_payment_successful:
    path:     /success
    defaults: { _controller: BrooterPaymentBundle:Payment:successful }

brooter_payment_cancel:
    path:     /cancel
    defaults: { _controller: BrooterPaymentBundle:Payment:cancel}


prepare:
    path:     /prepare
    defaults: { _controller: BrooterPaymentBundle:Payment:preparePaypalExpressCheckoutPayment }

