brooter_blog_homepage:
    path:     /
    defaults: { _controller: BrooterBlogBundle:Default:index }

brooter_blog_showpage:
    path:     /show/{id}
    defaults: { _controller: BrooterBlogBundle:Default:show }

brooter_blog_editpage:
    path:     /edit/{id}
    defaults: { _controller: BrooterAdminBundle:Post:edit }

