<?php

namespace Brooter\AdminBundle\Repository;

/**
 * AdvertisementPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
