<?php

namespace Brooter\AdminBundle\Repository;

/**
 * AgeOfPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgeOfPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
