<?php

namespace Brooter\AdminBundle\Repository;

/**
 * AreaInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaInRepository extends \Doctrine\ORM\EntityRepository
{
}
