<?php

namespace Brooter\AdminBundle\Repository;

/**
 * AvailabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
