<?php

namespace Brooter\AdminBundle\Repository;

/**
 * FaqCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
