<?php

namespace Brooter\AdminBundle\Repository;

/**
 * furnishedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class furnishedRepository extends \Doctrine\ORM\EntityRepository
{
}
