<?php

namespace Brooter\AdminBundle\Repository;

/**
 * ListPropForRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListPropForRepository extends \Doctrine\ORM\EntityRepository
{
}
