<?php

namespace Brooter\AdminBundle\Repository;

/**
 * MaterialUsedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialUsedRepository extends \Doctrine\ORM\EntityRepository
{
}
