<?php

namespace Brooter\AdminBundle\Repository;

/**
 * OverlookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OverlookingRepository extends \Doctrine\ORM\EntityRepository
{
}
