<?php

namespace Brooter\AdminBundle\Repository;

/**
 * PropertyAreaCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyAreaCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
