<?php

namespace Brooter\AdminBundle\Repository;

/**
 * PropFeatureAmenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropFeatureAmenRepository extends \Doctrine\ORM\EntityRepository
{
}
