<?php

namespace Brooter\AdminBundle\Repository;

/**
 * PropPossesionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropPossesionRepository extends \Doctrine\ORM\EntityRepository
{
}
