<?php

namespace Brooter\AdminBundle\Repository;

/**
 * PropertyCateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyCateRepository extends \Doctrine\ORM\EntityRepository
{
}
