<?php

namespace Brooter\AdminBundle\Repository;

/**
 * PropSubCateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropSubCateRepository extends \Doctrine\ORM\EntityRepository
{
}
