<?php

namespace Brooter\AdminBundle\Repository;

/**
 * PropertyFacingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyFacingRepository extends \Doctrine\ORM\EntityRepository
{
}
