<?php

namespace Brooter\AdminBundle\Repository;

/**
 * PropertyOnFloorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyOnFloorRepository extends \Doctrine\ORM\EntityRepository
{
}
