<?php

namespace Brooter\AdminBundle\Repository;

/**
 * ReservedParkingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservedParkingRepository extends \Doctrine\ORM\EntityRepository
{
}
