<?php

namespace Brooter\AdminBundle\Repository;

/**
 * TypeOfFlooringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfFlooringRepository extends \Doctrine\ORM\EntityRepository
{
}
