<?php

namespace Brooter\AdminBundle\Repository;

/**
 * WaterSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaterSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
