floorplans_index:
    path:     /
    defaults: { _controller: "BrooterPropertyBundle:FloorPlans:index" }
    methods:  GET

floorplans_show:
    path:     /{id}/show
    defaults: { _controller: "BrooterPropertyBundle:FloorPlans:show" }
    methods:  GET

floorplans_new:
    path:     /new
    defaults: { _controller: "BrooterPropertyBundle:FloorPlans:new" }
    methods:  [GET, POST]

floorplans_edit:
    path:     /{id}/edit
    defaults: { _controller: "BrooterPropertyBundle:FloorPlans:edit" }
    methods:  [GET, POST]

floorplans_delete:
    path:     /{id}/delete
    defaults: { _controller: "BrooterPropertyBundle:FloorPlans:delete" }
    methods:  DELETE
