# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    brooter.form.registration:
        class: Brooter\UserBundle\Form\RegistrationType
        arguments:
            - %fos_user.model.user.class%
        tags:
            - { name: form.type, alias: brooter_user_registration }
    brooter.admin.slider_uploader:
            class: Brooter\AdminBundle\FileUploader
            arguments: ['%sliders_directory%']
    brooter.admin.postimage_uploader:
            class: Brooter\AdminBundle\FileUploader
            arguments: ['%posts_directory%']
    brooter.property.prop_post_uploader:
            class: Brooter\AdminBundle\FileUploader
            arguments: ['%propImgs_directory%']
    brooter.property.floor_plan_uploader:
            class: Brooter\AdminBundle\FileUploader
            arguments: ['%floorImgs_directory%']