area_index:
    path:     /
    defaults: { _controller: "BrooterAdminBundle:Area:index" }
    methods:  GET

area_show:
    path:     /{id}/show
    defaults: { _controller: "BrooterAdminBundle:Area:show" }
    methods:  GET

area_new:
    path:     /new
    defaults: { _controller: "BrooterAdminBundle:Area:new" }
    methods:  [GET, POST]

area_edit:
    path:     /{id}/edit
    defaults: { _controller: "BrooterAdminBundle:Area:edit" }
    methods:  [GET, POST]

area_delete:
    path:     /{id}/delete
    defaults: { _controller: "BrooterAdminBundle:Area:delete" }
    methods:  DELETE
