faqcategory_index:
    path:     /
    defaults: { _controller: "BrooterAdminBundle:FaqCategory:index" }
    methods:  GET

faqcategory_show:
    path:     /{id}/show
    defaults: { _controller: "BrooterAdminBundle:FaqCategory:show" }
    methods:  GET

faqcategory_new:
    path:     /new
    defaults: { _controller: "BrooterAdminBundle:FaqCategory:new" }
    methods:  [GET, POST]

faqcategory_edit:
    path:     /{id}/edit
    defaults: { _controller: "BrooterAdminBundle:FaqCategory:edit" }
    methods:  [GET, POST]

faqcategory_delete:
    path:     /{id}/delete
    defaults: { _controller: "BrooterAdminBundle:FaqCategory:delete" }
    methods:  DELETE
