materialused_index:
    path:     /
    defaults: { _controller: "BrooterAdminBundle:MaterialUsed:index" }
    methods:  GET

materialused_show:
    path:     /{id}/show
    defaults: { _controller: "BrooterAdminBundle:MaterialUsed:show" }
    methods:  GET

materialused_new:
    path:     /new
    defaults: { _controller: "BrooterAdminBundle:MaterialUsed:new" }
    methods:  [GET, POST]

materialused_edit:
    path:     /{id}/edit
    defaults: { _controller: "BrooterAdminBundle:MaterialUsed:edit" }
    methods:  [GET, POST]

materialused_delete:
    path:     /{id}/delete
    defaults: { _controller: "BrooterAdminBundle:MaterialUsed:delete" }
    methods:  DELETE
