propertyfacing_index:
    path:     /
    defaults: { _controller: "BrooterAdminBundle:PropertyFacing:index" }
    methods:  GET

propertyfacing_show:
    path:     /{id}/show
    defaults: { _controller: "BrooterAdminBundle:PropertyFacing:show" }
    methods:  GET

propertyfacing_new:
    path:     /new
    defaults: { _controller: "BrooterAdminBundle:PropertyFacing:new" }
    methods:  [GET, POST]

propertyfacing_edit:
    path:     /{id}/edit
    defaults: { _controller: "BrooterAdminBundle:PropertyFacing:edit" }
    methods:  [GET, POST]

propertyfacing_delete:
    path:     /{id}/delete
    defaults: { _controller: "BrooterAdminBundle:PropertyFacing:delete" }
    methods:  DELETE
