reservedparking_index:
    path:     /
    defaults: { _controller: "BrooterAdminBundle:ReservedParking:index" }
    methods:  GET

reservedparking_show:
    path:     /{id}/show
    defaults: { _controller: "BrooterAdminBundle:ReservedParking:show" }
    methods:  GET

reservedparking_new:
    path:     /new
    defaults: { _controller: "BrooterAdminBundle:ReservedParking:new" }
    methods:  [GET, POST]

reservedparking_edit:
    path:     /{id}/edit
    defaults: { _controller: "BrooterAdminBundle:ReservedParking:edit" }
    methods:  [GET, POST]

reservedparking_delete:
    path:     /{id}/delete
    defaults: { _controller: "BrooterAdminBundle:ReservedParking:delete" }
    methods:  DELETE
