typeofflooring_index:
    path:     /
    defaults: { _controller: "BrooterAdminBundle:TypeOfFlooring:index" }
    methods:  GET

typeofflooring_show:
    path:     /{id}/show
    defaults: { _controller: "BrooterAdminBundle:TypeOfFlooring:show" }
    methods:  GET

typeofflooring_new:
    path:     /new
    defaults: { _controller: "BrooterAdminBundle:TypeOfFlooring:new" }
    methods:  [GET, POST]

typeofflooring_edit:
    path:     /{id}/edit
    defaults: { _controller: "BrooterAdminBundle:TypeOfFlooring:edit" }
    methods:  [GET, POST]

typeofflooring_delete:
    path:     /{id}/delete
    defaults: { _controller: "BrooterAdminBundle:TypeOfFlooring:delete" }
    methods:  DELETE
