brooter_property_postproperty:
    resource: "@BrooterPropertyBundle/Resources/config/routing/postproperty.yml"
    prefix:   /postproperty

brooter_property_homepage:
    path:     /
    defaults: { _controller: BrooterPropertyBundle:Default:index }

brooter_property_floorplans:
    resource: "@BrooterPropertyBundle/Resources/config/routing/floorplans.yml"
    prefix:   /floorplans
