<?php

namespace Brooter\AdvertisementBundle\Repository;

/**
 * AdverUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdverUserRepository extends \Doctrine\ORM\EntityRepository
{
}
