<?php

namespace Brooter\PropertyBundle\Repository;

/**
 * FloorPlansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FloorPlansRepository extends \Doctrine\ORM\EntityRepository
{
}
