<?php

namespace Brooter\PropertyBundle\Repository;

/**
 * PostPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
