<?php

namespace Brooter\PropertyBundle\Repository;

/**
 * PropertySpecificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertySpecificationRepository extends \Doctrine\ORM\EntityRepository
{
}
