<?php

namespace Brooter\PropertyBundle\Repository;

/**
 * PropertyImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyImageRepository extends \Doctrine\ORM\EntityRepository
{
}
