<?php

namespace Brooter\PropertyBundle\Repository;

/**
 * YearBuiltRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearBuiltRepository extends \Doctrine\ORM\EntityRepository
{
}
