brooter_admin_post:
    resource: "@BrooterAdminBundle/Resources/config/routing/post.yml"
    prefix:   /post

brooter_admin_category:
    resource: "@BrooterAdminBundle/Resources/config/routing/category.yml"
    prefix:   /category

brooter_admin_slider:
    resource: "@BrooterAdminBundle/Resources/config/routing/slider.yml"
    prefix:   /slider

brooter_admin_homepage:
    path:     /
    defaults: { _controller: BrooterAdminBundle:Default:index }
